import "./globals.css";
import { Inter } from "next/font/google";
import { getServerSession } from "next-auth";
// import Navbar from "./components/Navbar";
import SessionProvider from "./components/SessionProvider";

import { ContextProvider } from "./context/customClient";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Beatleap",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <QueryClientProvider client={queryClient}> */}
        <SessionProvider session={session}>
          <ContextProvider>
            <main className=" text-white">
              {/* <Navbar /> */}
              {children}
            </main>
          </ContextProvider>
        </SessionProvider>
        {/* </QueryClientProvider> */}
      </body>
    </html>
  );
}
